version: "3.11"

services:
  web:
    build: .
    command: sh -c "python laboratoire_bj/manage.py makemigrations && python laboratoire_bj/manage.py migrate && python laboratoire_bj/manage.py populer_table_produits && python laboratoire_bj/manage.py runserver 0.0.0.0:5000"
    container_name: lab0-container-bryanjoya
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
