global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django-services"
    metrics_path: /metrics/
    static_configs:
      - targets:
        - "produits:8000"
        - "stocks:8000"
        - "carts:8000"
        - "accounts:8000"
        - "rapports:8000"
        - "web:8000"
