global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["web:8000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]